In [6]:
import numpy as np
import scipy.stats as stats
import pandas as pd
import csv 
from matplotlib import pyplot
from numpy import nan

In [7]:
DF = pd.read_csv("IPL_Twitter_MissingData.csv")#,header=None)

# 1.Finding the no. of missing data samples

In [8]:
row_wise_nanvalues = pd.DataFrame(DF.isna().sum(axis = 1))
row_missing_value = pd.DataFrame(row_wise_nanvalues[0] > 0)
nan_samples = np.sum(row_missing_value[0])
print('If the column vector (Q1, Q2, X1, X2, X3, X4) represents a sample, then having at least one missing value in the sample includes it in missing values sample. So,'+ str(nan_samples)+ ' data samples are missing.')

If the column vector (Q1, Q2, X1, X2, X3, X4) represents a sample, then having at least one missing value in the sample includes it in missing values sample. So,238 data samples are missing.


In [9]:
column_wise_nanvalues = pd.DataFrame(DF.isnull().sum(axis = 0))
type(column_wise_nanvalues) #data frame
column_wise_nanvalues.columns = ['number of values missing from each column']
column_wise_nanvalues

number of values missing from each column
Q1                                         44
Q2                                         45
X1                                         36
X2                                         55
X3                                         67
X4                                         41

# 3. Obtaining the linear relationships between the variables(X1, X2, X3, X4)
    a*X1+b*X2+c*X3+d=X4

# a. For whole data

In [10]:
DF = pd.read_csv("IPL_Twitter_MissingData.csv")#,header=None)
DF1 = DF.dropna()

In [11]:
data_matrix = DF1.values
X_4 = data_matrix[:,5]
X = data_matrix[:,[2,3,4]]
X = np.c_[np.ones((762,1)),X]

In [12]:
theta = np.matmul(np.linalg.pinv(X),X_4)
print(theta)


[ 3.47855945e+03  7.83187972e-01  8.27473413e-02 -3.29093424e-01]


# Finding correlation

In [13]:
temp_pearsonr= np.zeros([(len(DF1.columns)-2),(len(DF1.columns)-2)])
for i in range(0,len(DF1.columns)-2):
    for j in range(0,len(DF1.columns)-2):
        temp_pearsonr[i,j] = stats.pearsonr(DF1[DF1.columns[i+2]],DF1[DF1.columns[j+2]])[0]
temp_pearsonr

array([[ 1.        , -0.40361389, -0.41196742,  0.62970423],
       [-0.40361389,  1.        ,  0.60391296, -0.35548608],
       [-0.41196742,  0.60391296,  1.        , -0.58395823],
       [ 0.62970423, -0.35548608, -0.58395823,  1.        ]])

In [253]:
(temp_pearsonr)>0.75 #strongly +vely linearly correlated ones wiht true

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [254]:
(temp_pearsonr)<-0.75 #strongly negatively correlated

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [255]:
((temp_pearsonr>0.45) & (temp_pearsonr<0.75))  #fairly linearly correlated

array([[False, False, False,  True],
       [False, False,  True, False],
       [False,  True, False, False],
       [ True, False, False, False]])

In [256]:
((temp_pearsonr<0.1) & (temp_pearsonr>-0.1)) #barely(not at all) linearly correlated ones wiht true

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [257]:
((temp_pearsonr<-0.45) & (temp_pearsonr>-0.75))  ##fairly linearly negatively correlated

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False,  True, False]])

# b. If there is no match for both CSK and MI

In [14]:
df= DF1.replace(1,nan)
DF2 = df.dropna()

In [15]:
data_matrix1 = DF2.values
X_4 = data_matrix1[:,5]
X = data_matrix1[:,[2,3,4]]
X = np.c_[np.ones((200,1)),X]

In [16]:
theta = np.matmul(np.linalg.pinv(X),X_4)
print(theta)


[-0.08227479  1.16667292  1.66670279 -1.33334455]


# Finding Correlation

In [17]:
temp_pearsonr= np.zeros([(len(DF2.columns)-2),(len(DF2.columns)-2)])
for i in range(0,len(DF2.columns)-2):
    for j in range(0,len(DF2.columns)-2):
        temp_pearsonr[i,j] = stats.pearsonr(DF2[DF2.columns[i+2]],DF2[DF2.columns[j+2]])[0]
temp_pearsonr

array([[ 1.        , -0.0330597 ,  0.16918214,  0.74525807],
       [-0.0330597 ,  1.        ,  0.04622996,  0.47564741],
       [ 0.16918214,  0.04622996,  1.        , -0.28149956],
       [ 0.74525807,  0.47564741, -0.28149956,  1.        ]])

In [262]:
(temp_pearsonr)>0.75 #strongly +vely linearly correlated ones wiht true

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [263]:
(temp_pearsonr)<-0.75 #strongly negatively correlated

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [264]:
((temp_pearsonr>0.45) & (temp_pearsonr<0.75))  #fairly linearly correlated

array([[False, False, False,  True],
       [False, False, False,  True],
       [False, False, False, False],
       [ True,  True, False, False]])

In [265]:
((temp_pearsonr<0.1) & (temp_pearsonr>-0.1)) #barely(not at all) linearly correlated ones wiht true

array([[False,  True, False, False],
       [ True, False,  True, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [266]:
((temp_pearsonr<-0.45) & (temp_pearsonr>-0.75))  ##fairly linearly negatively correlated

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

# c. If there is no match for CSK but there is match for MI

In [18]:
DFc = DF1[(DF1.Q1 == 0) & (DF.Q2 == 1)]


C:\Users\ashwi\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


In [19]:
data_matrix_c = DFc.values
X_4 = data_matrix_c[:,5]
X = data_matrix_c[:,[2,3,4]]
X = np.c_[np.ones((187,1)),X]

In [20]:
theta = np.matmul(np.linalg.pinv(X),X_4)
print(theta)


[-0.1944767  -0.24999005  0.99998699 -0.34997891]


# Finding correlation

In [21]:
temp_pearsonr= np.zeros([(len(DFc.columns)-2),(len(DFc.columns)-2)])
for i in range(0,len(DFc.columns)-2):
    for j in range(0,len(DFc.columns)-2):
        temp_pearsonr[i,j] = stats.pearsonr(DFc[DFc.columns[i+2]],DFc[DFc.columns[j+2]])[0]
temp_pearsonr

array([[ 1.        ,  0.11529097,  0.07633152, -0.11390326],
       [ 0.11529097,  1.        ,  0.12538542,  0.91076194],
       [ 0.07633152,  0.12538542,  1.        , -0.24530123],
       [-0.11390326,  0.91076194, -0.24530123,  1.        ]])

In [271]:
(temp_pearsonr)>0.75 #strongly +vely linearly correlated ones wiht true

array([[ True, False, False, False],
       [False,  True, False,  True],
       [False, False,  True, False],
       [False,  True, False,  True]])

In [272]:
(temp_pearsonr)<-0.75 #strongly negatively correlated

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [273]:
((temp_pearsonr>0.45) & (temp_pearsonr<0.75))  #fairly linearly correlated

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [274]:
((temp_pearsonr<0.1) & (temp_pearsonr>-0.1)) #barely(not at all) linearly correlated ones wiht true

array([[False, False,  True, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False]])

In [275]:
((temp_pearsonr<-0.45) & (temp_pearsonr>-0.75))  ##fairly linearly negatively correlated

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

# d. If there is no match for MI but there is match for CSK

In [22]:
DFd = DF1[(DF1.Q1 == 1) & (DF.Q2 == 0)]

C:\Users\ashwi\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


In [23]:
data_matrix_d = DFd.values
X_4 = data_matrix_d[:,5]
X = data_matrix_d[:,[2,3,4]]
X = np.c_[np.ones((175,1)),X]

In [24]:
theta = np.matmul(np.linalg.pinv(X),X_4)
print(theta)

[-0.25419187 -0.49997534 -0.66665269  1.7500029 ]


# Finding Correlation

In [25]:
temp_pearsonr= np.zeros([(len(DFd.columns)-2),(len(DFd.columns)-2)])
for i in range(0,len(DFd.columns)-2):
    for j in range(0,len(DFd.columns)-2):
        temp_pearsonr[i,j] = stats.pearsonr(DFd[DFd.columns[i+2]],DFd[DFd.columns[j+2]])[0]
temp_pearsonr

array([[ 1.        , -0.06966482,  0.04393471, -0.18180059],
       [-0.06966482,  1.        ,  0.13348292, -0.27227738],
       [ 0.04393471,  0.13348292,  1.        ,  0.88407857],
       [-0.18180059, -0.27227738,  0.88407857,  1.        ]])

In [280]:
(temp_pearsonr)>0.75 #strongly +vely linearly correlated ones wiht true

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True,  True],
       [False, False,  True,  True]])

In [281]:
(temp_pearsonr)<-0.75 #strongly negatively correlated

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [282]:
((temp_pearsonr>0.45) & (temp_pearsonr<0.75))  #fairly linearly correlated

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [283]:
((temp_pearsonr<0.1) & (temp_pearsonr>-0.1)) #barely(not at all) linearly correlated ones wiht true

array([[False,  True,  True, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [False, False, False, False]])

In [284]:
((temp_pearsonr<-0.45) & (temp_pearsonr>-0.75))  ##fairly linearly negatively correlated

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

# e. If there is match for both MI and CSK.

In [26]:
df= DF1.replace(0,nan)
DF3 = df.dropna()

In [27]:
data_matrix2 = DF3.values
X_4 = data_matrix2[:,5]
X = data_matrix2[:,[2,3,4]]
X = np.c_[np.ones((200,1)),X]

In [28]:
theta = np.matmul(np.linalg.pinv(X),X_4)
print(theta)


[ 0.20017767  0.86667819  0.66666002 -0.66667511]


In [29]:
temp_pearsonr= np.zeros([(len(DF3.columns)-2),(len(DF3.columns)-2)])
for i in range(0,len(DF3.columns)-2):
    for j in range(0,len(DF3.columns)-2):
        temp_pearsonr[i,j] = stats.pearsonr(DF3[DF3.columns[i+2]],DF3[DF3.columns[j+2]])[0]
temp_pearsonr

array([[ 1.        , -0.1481224 ,  0.00768595,  0.53249234],
       [-0.1481224 ,  1.        ,  0.04886459,  0.4872226 ],
       [ 0.00768595,  0.04886459,  1.        , -0.5896862 ],
       [ 0.53249234,  0.4872226 , -0.5896862 ,  1.        ]])

In [289]:
(temp_pearsonr)>0.75 #strongly +vely linearly correlated ones wiht true

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [290]:
(temp_pearsonr)<-0.75 #strongly negatively correlated

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [291]:
((temp_pearsonr>0.45) & (temp_pearsonr<0.75))  #fairly linearly correlated

array([[False, False, False,  True],
       [False, False, False,  True],
       [False, False, False, False],
       [ True,  True, False, False]])

In [292]:
((temp_pearsonr<0.1) & (temp_pearsonr>-0.1)) #barely(not at all) linearly correlated ones wiht true

array([[False, False,  True, False],
       [False, False,  True, False],
       [ True,  True, False, False],
       [False, False, False, False]])

In [293]:
((temp_pearsonr<-0.45) & (temp_pearsonr>-0.75))  ##fairly linearly negatively correlated

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False,  True, False]])

# 4. Imputing the missing values

# Filling by mean
   Filling missing values in X1, X2, X3, X4 columns by their means

In [294]:
DF = pd.read_csv("IPL_Twitter_MissingData.csv")#,header=None)
DF_X = DF[['X1','X2','X3','X4']]
DF_Q = DF[['Q1','Q2']]
DF_X['X1'] = DF_X['X1'].fillna(int(DF_X['X1'].mean()))
DF_X['X2'] = DF_X['X2'].fillna(int(DF_X['X2'].mean()))
DF_X['X3'] = DF_X['X3'].fillna(int(DF_X['X3'].mean()))
DF_X['X4'] = DF_X['X4'].fillna(int(DF_X['X4'].mean()))
print(DF_X)

         X1       X2       X3       X4
0    8130.0   4838.0   3623.0  12718.0
1    2594.0   3651.0   2323.0   6014.0
2    4108.0  12510.0  12127.0   3816.0
3    2171.0   8895.0   6732.0   1357.0
4    4518.0   4326.0   4214.0   6862.0
5    4218.0   9931.0  10149.0   5324.0
6    1916.0   8210.0  12422.0   3383.0
7    1470.0   8204.0  11644.0   3761.0
8    7109.0   4031.0   3973.0   9715.0
9    2728.0   8895.0   8562.0   5144.0
10   4584.0   5495.0  10220.0    772.0
11   3031.0  14284.0  11921.0   4202.0
12   4366.0  14286.0   9819.0   5476.0
13   4572.0  11782.0   7732.0   3390.0
14   2293.0  13848.0   6170.0    419.0
15   2585.0  13526.0   7793.0   3328.0
16   2772.0  12740.0  12834.0   2340.0
17   2284.0  14148.0   9111.0   5370.0
18   2969.0   8474.0  14864.0   2529.0
19   9818.0   2755.0   1444.0  14121.0
20   3960.0   6174.0  13675.0    398.0
21   3451.0   9097.0  12659.0   3804.0
22   3278.0  10307.0   7481.0   4581.0
23   1381.0  11763.0  12967.0    394.0
24   4952.0   9321.0  119

C:\Users\ashwi\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\ashwi\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\ashwi\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_i

# Filling by median
   Filling missing values in X1, X2, X3, X4 columns by their median

In [295]:
DF = pd.read_csv("IPL_Twitter_MissingData.csv")#,header=None)
DF_X = DF[['X1','X2','X3','X4']]
DF_X['X1'] = DF_X['X1'].fillna(int(DF_X['X1'].median()))
DF_X['X2'] = DF_X['X2'].fillna(int(DF_X['X2'].median()))
DF_X['X3'] = DF_X['X3'].fillna(int(DF_X['X3'].median()))
DF_X['X4'] = DF_X['X4'].fillna(int(DF_X['X4'].median()))
print(DF_X)

         X1       X2       X3       X4
0    8130.0   4838.0   3623.0  12718.0
1    2594.0   3651.0   2323.0   6014.0
2    4108.0  12510.0  12127.0   3816.0
3    2171.0   9924.0   6732.0   1357.0
4    4518.0   4326.0   4214.0   6862.0
5    4218.0   9931.0  10149.0   5324.0
6    1916.0   8210.0  12422.0   3383.0
7    1470.0   8204.0  11644.0   3761.0
8    7109.0   4031.0   3973.0   9715.0
9    2728.0   9924.0   8562.0   5144.0
10   4584.0   5495.0  10220.0    772.0
11   3031.0  14284.0  11921.0   4202.0
12   4366.0  14286.0   9819.0   5476.0
13   4572.0  11782.0   7732.0   3390.0
14   2293.0  13848.0   6170.0    419.0
15   2585.0  13526.0   7793.0   3328.0
16   2772.0  12740.0  12834.0   2340.0
17   2284.0  14148.0   9111.0   5370.0
18   2969.0   8474.0  14864.0   2529.0
19   9818.0   2755.0   1444.0  14121.0
20   3960.0   6174.0  13675.0    398.0
21   3451.0   9097.0  12659.0   3804.0
22   3278.0  10307.0   7481.0   4581.0
23   1381.0  11763.0  12967.0    394.0
24   4952.0   9321.0  119

C:\Users\ashwi\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\ashwi\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\ashwi\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is 

# Fill Q1 and Q2 by 1 if the number of 1 are more than 0's that is if (sum of entries in Q1/total entries after deleting nan entries in the column) is greater than 0.5

In [296]:
#fill Q1 and Q2 by 1 if the number of 1 are more than 0's that is if (sum of entries in Q1/total entries after deleting nan entries in the column)
DF2 = pd.read_csv("IPL_Twitter_MissingData.csv")#,header=None)
temp_col = DF2['Q1'].dropna()
checkQ1 = sum(temp_col)/temp_col.size
checkQ2 = sum(DF2['Q2'].dropna())/(DF2['Q1'].dropna().size)
# print(checkQ1,checkQ2)
if checkQ1>=0.5:
    DF2['Q1'].fillna(1)
else:
    DF2['Q1'] = DF2['Q1'].fillna(0)
#     pass
if checkQ2>=0.5:
    DF2['Q2'].fillna(1)
else:
    DF2['Q2'] = DF2['Q2'].fillna(0)
#     pass
print(DF2[['Q1','Q2']])

      Q1   Q2
0    0.0  0.0
1    0.0  0.0
2    1.0  1.0
3    1.0  0.0
4    0.0  0.0
5    0.0  1.0
6    0.0  0.0
7    0.0  1.0
8    0.0  0.0
9    1.0  0.0
10   0.0  1.0
11   1.0  1.0
12   1.0  0.0
13   1.0  0.0
14   1.0  0.0
15   1.0  0.0
16   1.0  1.0
17   1.0  0.0
18   0.0  1.0
19   0.0  0.0
20   0.0  1.0
21   0.0  1.0
22   1.0  0.0
23   1.0  1.0
24   0.0  1.0
25   1.0  0.0
26   0.0  0.0
27   1.0  0.0
28   1.0  1.0
29   0.0  1.0
..   ...  ...
970  1.0  1.0
971  0.0  0.0
972  1.0  0.0
973  1.0  1.0
974  0.0  0.0
975  0.0  1.0
976  1.0  1.0
977  1.0  1.0
978  0.0  0.0
979  0.0  1.0
980  0.0  1.0
981  0.0  1.0
982  0.0  0.0
983  0.0  1.0
984  1.0  0.0
985  0.0  0.0
986  1.0  0.0
987  0.0  1.0
988  0.0  0.0
989  0.0  0.0
990  1.0  1.0
991  1.0  1.0
992  0.0  1.0
993  0.0  0.0
994  1.0  1.0
995  1.0  0.0
996  0.0  1.0
997  0.0  0.0
998  1.0  1.0
999  1.0  1.0

[1000 rows x 2 columns]


# Using ffill and bfill to impute the missing values

In [297]:
DF3 = pd.read_csv("IPL_Twitter_MissingData.csv")#,header=None)
DF3[['Q1','Q2']] = DF3[['Q1','Q2']].bfill()
print(DF3)

      Q1   Q2      X1       X2       X3       X4
0    0.0  0.0  8130.0   4838.0   3623.0  12718.0
1    0.0  0.0  2594.0   3651.0   2323.0   6014.0
2    1.0  1.0  4108.0  12510.0  12127.0   3816.0
3    1.0  0.0  2171.0      NaN   6732.0   1357.0
4    0.0  0.0  4518.0   4326.0   4214.0   6862.0
5    0.0  1.0  4218.0   9931.0  10149.0   5324.0
6    0.0  1.0  1916.0   8210.0  12422.0   3383.0
7    0.0  1.0  1470.0   8204.0  11644.0   3761.0
8    0.0  0.0  7109.0   4031.0   3973.0   9715.0
9    1.0  0.0  2728.0      NaN   8562.0   5144.0
10   0.0  1.0  4584.0   5495.0  10220.0    772.0
11   1.0  1.0  3031.0  14284.0  11921.0   4202.0
12   1.0  0.0  4366.0  14286.0   9819.0   5476.0
13   1.0  0.0  4572.0  11782.0   7732.0   3390.0
14   1.0  0.0  2293.0  13848.0   6170.0    419.0
15   1.0  0.0  2585.0  13526.0   7793.0   3328.0
16   1.0  1.0  2772.0  12740.0  12834.0   2340.0
17   1.0  0.0  2284.0  14148.0   9111.0   5370.0
18   0.0  1.0  2969.0   8474.0  14864.0   2529.0
19   0.0  0.0  9818.

In [298]:
DF4 = pd.read_csv("IPL_Twitter_MissingData.csv")#,header=None)
DF4[['Q1','Q2']] = DF4[['Q1','Q2']].bfill()
print(DF4)

      Q1   Q2      X1       X2       X3       X4
0    0.0  0.0  8130.0   4838.0   3623.0  12718.0
1    0.0  0.0  2594.0   3651.0   2323.0   6014.0
2    1.0  1.0  4108.0  12510.0  12127.0   3816.0
3    1.0  0.0  2171.0      NaN   6732.0   1357.0
4    0.0  0.0  4518.0   4326.0   4214.0   6862.0
5    0.0  1.0  4218.0   9931.0  10149.0   5324.0
6    0.0  1.0  1916.0   8210.0  12422.0   3383.0
7    0.0  1.0  1470.0   8204.0  11644.0   3761.0
8    0.0  0.0  7109.0   4031.0   3973.0   9715.0
9    1.0  0.0  2728.0      NaN   8562.0   5144.0
10   0.0  1.0  4584.0   5495.0  10220.0    772.0
11   1.0  1.0  3031.0  14284.0  11921.0   4202.0
12   1.0  0.0  4366.0  14286.0   9819.0   5476.0
13   1.0  0.0  4572.0  11782.0   7732.0   3390.0
14   1.0  0.0  2293.0  13848.0   6170.0    419.0
15   1.0  0.0  2585.0  13526.0   7793.0   3328.0
16   1.0  1.0  2772.0  12740.0  12834.0   2340.0
17   1.0  0.0  2284.0  14148.0   9111.0   5370.0
18   0.0  1.0  2969.0   8474.0  14864.0   2529.0
19   0.0  0.0  9818.

In [299]:
DF3[['X1','X2','X3','X4']] = DF3[['X1','X2','X3','X4']].bfill()
DF4[['X1','X2','X3','X4']] = DF4[['X1','X2','X3','X4']].ffill()
print(DF3)
print(DF4)

      Q1   Q2      X1       X2       X3       X4
0    0.0  0.0  8130.0   4838.0   3623.0  12718.0
1    0.0  0.0  2594.0   3651.0   2323.0   6014.0
2    1.0  1.0  4108.0  12510.0  12127.0   3816.0
3    1.0  0.0  2171.0   4326.0   6732.0   1357.0
4    0.0  0.0  4518.0   4326.0   4214.0   6862.0
5    0.0  1.0  4218.0   9931.0  10149.0   5324.0
6    0.0  1.0  1916.0   8210.0  12422.0   3383.0
7    0.0  1.0  1470.0   8204.0  11644.0   3761.0
8    0.0  0.0  7109.0   4031.0   3973.0   9715.0
9    1.0  0.0  2728.0   5495.0   8562.0   5144.0
10   0.0  1.0  4584.0   5495.0  10220.0    772.0
11   1.0  1.0  3031.0  14284.0  11921.0   4202.0
12   1.0  0.0  4366.0  14286.0   9819.0   5476.0
13   1.0  0.0  4572.0  11782.0   7732.0   3390.0
14   1.0  0.0  2293.0  13848.0   6170.0    419.0
15   1.0  0.0  2585.0  13526.0   7793.0   3328.0
16   1.0  1.0  2772.0  12740.0  12834.0   2340.0
17   1.0  0.0  2284.0  14148.0   9111.0   5370.0
18   0.0  1.0  2969.0   8474.0  14864.0   2529.0
19   0.0  0.0  9818.